;;; org-roam-lies-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from org-roam-lies.el

(register-definition-prefixes "org-roam-lies" '("create-org-roam-lies-node" "day-start-and-end-times" "iso-week-to-time" "make-template" "month-start-and-end-times" "node-start-and-end-times" "org-roam-lies-" "orl-" "quarter-start-and-end-times" "time-" "week-start-and-end-times" "year-start-and-end-times"))


;;; End of scraped data

(provide 'org-roam-lies-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-roam-lies-autoloads.el ends here
